# Generated by Django 4.2.11 on 2026-01-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profile_url',
            new_name='user_image_url',
        ),
    ]
