# Generated by Django 4.2.11 on 2026-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='소셜 ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='소셜 로그인 제공자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결제 수단'),
        ),
    ]
