# Generated by Django 4.2.11 on 2026-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_social_login_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='키(cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='몸무게(kg)'),
        ),
    ]
