# Generated by Django 4.2.11 on 2026-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile_url_user_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결제 수단'),
        ),
    ]
