# Generated by Django 4.2.11 on 2026-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box X1')),
                ('bbox_y1', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box Y1')),
                ('bbox_x2', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box X2')),
                ('bbox_y2', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box Y2')),
                ('object_category', models.CharField(help_text='검출된 객체의 카테고리 (상의, 하의, 신발 등)', max_length=100, verbose_name='객체 카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '검출된 객체',
                'verbose_name_plural': '검출된 객체 목록',
                'db_table': 'detected_object',
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_analysis_status', models.CharField(choices=[('PENDING', '대기 중'), ('RUNNING', '분석 중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='분석 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '이미지 분석',
                'verbose_name_plural': '이미지 분석 목록',
                'db_table': 'image_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='코사인 유사도 (0~1)', verbose_name='신뢰도 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '객체-상품 매핑',
                'verbose_name_plural': '객체-상품 매핑 목록',
                'db_table': 'object_product_mapping',
            },
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_product_inventory', models.PositiveIntegerField(default=0, verbose_name='선택 상품 재고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '선택된 상품',
                'verbose_name_plural': '선택된 상품 목록',
                'db_table': 'selected_product',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image_url', models.ImageField(upload_to='uploaded-images/%Y/%m/%d/', verbose_name='업로드한 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '업로드된 이미지',
                'verbose_name_plural': '업로드된 이미지 목록',
                'db_table': 'uploaded_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
