# Generated by Django 4.2.11 on 2026-01-11 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image_url', models.ImageField(upload_to='uploaded-images/%Y/%m/%d/', verbose_name='업로드한 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
            options={
                'db_table': 'uploaded_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
