# Generated by Django 4.2.11 on 2026-01-11 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded-images/%Y/%m/%d/', verbose_name='이미지 파일')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'db_table': 'uploaded_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
