# Generated by Django 4.2.11 on 2026-01-13 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='products.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='size_code',
            field=models.ForeignKey(blank=True, db_column='size_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='products.sizecode', verbose_name='사이즈 코드'),
        ),
        migrations.AddField(
            model_name='objectproductmapping',
            name='detected_object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='analyses.detectedobject', verbose_name='검출된 객체'),
        ),
        migrations.AddField(
            model_name='objectproductmapping',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_mappings', to='products.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='uploaded_image',
            field=models.ForeignKey(db_column='uploaded_image_id', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyses.uploadedimage', verbose_name='업로드된 이미지'),
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='uploaded_image',
            field=models.ForeignKey(db_column='uploaded_image_id', on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='analyses.uploadedimage', verbose_name='업로드된 이미지'),
        ),
    ]
