# Generated by Django 4.2.11 on 2026-01-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x1', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box X1')),
                ('bbox_y1', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box Y1')),
                ('bbox_x2', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box X2')),
                ('bbox_y2', models.FloatField(default=0.0, help_text='정규화된 좌표 (0~1)', verbose_name='Bounding Box Y2')),
                ('object_category', models.CharField(help_text='검출된 객체의 카테고리 (상의, 하의, 신발 등)', max_length=100, verbose_name='객체 카테고리')),
                ('confidence', models.FloatField(default=0.0, help_text='0.0 ~ 1.0 사이의 값', verbose_name='신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '검출된 객체',
                'verbose_name_plural': '검출된 객체 목록',
                'db_table': 'detected_object',
            },
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-created_at'], 'verbose_name': '업로드된 이미지', 'verbose_name_plural': '업로드된 이미지 목록'},
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_product_inventory', models.PositiveIntegerField(default=0, verbose_name='선택 상품 재고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='products.product', verbose_name='상품')),
                ('size_code', models.ForeignKey(blank=True, db_column='size_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='products.sizecode', verbose_name='사이즈 코드')),
            ],
            options={
                'verbose_name': '선택된 상품',
                'verbose_name_plural': '선택된 상품 목록',
                'db_table': 'selected_product',
            },
        ),
        migrations.CreateModel(
            name='ObjectProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='코사인 유사도 (0~1)', verbose_name='신뢰도 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('detected_object', models.ForeignKey(db_column='detected_object_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='analyses.detectedobject', verbose_name='검출된 객체')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='object_mappings', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '객체-상품 매핑',
                'verbose_name_plural': '객체-상품 매핑 목록',
                'db_table': 'object_product_mapping',
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_analysis_status', models.CharField(choices=[('PENDING', '대기 중'), ('RUNNING', '분석 중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='분석 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('uploaded_image', models.ForeignKey(db_column='uploaded_image_id', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyses.uploadedimage', verbose_name='업로드된 이미지')),
            ],
            options={
                'verbose_name': '이미지 분석',
                'verbose_name_plural': '이미지 분석 목록',
                'db_table': 'image_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='uploaded_image',
            field=models.ForeignKey(db_column='uploaded_image_id', on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='analyses.uploadedimage', verbose_name='업로드된 이미지'),
        ),
    ]
