# Generated by Django 4.2.11 on 2026-01-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_detectedobject_alter_uploadedimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedobject',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='objectproductmapping',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='objectproductmapping',
            name='detected_object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='analyses.detectedobject', verbose_name='검출된 객체'),
        ),
    ]
