# Generated by Django 4.2.11 on 2026-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True이면 피드에 공개됨', verbose_name='공개 여부'),
        ),
    ]
