# Generated by Django 4.2.11 on 2026-01-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_add_is_public_to_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobject',
            name='cropped_image_url',
            field=models.URLField(blank=True, help_text='GCS에 저장된 크롭된 이미지 URL', max_length=1000, null=True, verbose_name='크롭 이미지 URL'),
        ),
    ]
