# Generated by Django 4.2.11 on 2026-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_add_cropped_image_url_to_detected_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_image_url',
            field=models.URLField(blank=True, help_text='GCS에 저장된 원본 이미지 URL', max_length=1000, null=True, verbose_name='업로드한 이미지 URL'),
        ),
    ]
