# Generated by Django 4.2.11 on 2026-01-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_change_uploaded_image_url_to_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='style_tag1',
            field=models.CharField(blank=True, help_text='메인 스타일 태그 (amekaji, casual, street 등)', max_length=50, null=True, verbose_name='스타일 태그 1'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='style_tag2',
            field=models.CharField(blank=True, help_text='서브 스타일 태그', max_length=50, null=True, verbose_name='스타일 태그 2'),
        ),
    ]
