# Generated by Django 4.2.11 on 2026-01-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FittingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting_image_status', models.CharField(choices=[('PENDING', '대기 중'), ('RUNNING', '처리 중'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='피팅 상태')),
                ('fitting_image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='피팅 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '가상 피팅 이미지',
                'verbose_name_plural': '가상 피팅 이미지 목록',
                'db_table': 'fitting_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image_url', models.ImageField(upload_to='user-images/%Y/%m/%d/', verbose_name='사용자 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '사용자 이미지',
                'verbose_name_plural': '사용자 이미지 목록',
                'db_table': 'user_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
