# Generated by Django 4.2.11 on 2026-01-13 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fittings', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='fittingimage',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='fitting_images', to='products.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='fittingimage',
            name='user_image',
            field=models.ForeignKey(db_column='user_image_id', on_delete=django.db.models.deletion.CASCADE, related_name='fitting_images', to='fittings.userimage', verbose_name='사용자 이미지'),
        ),
    ]
