# Generated by Django 4.2.11 on 2026-01-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '장바구니 항목',
                'verbose_name_plural': '장바구니 항목 목록',
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='총 주문 금액')),
                ('delivery_address', models.TextField(verbose_name='배송 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.PositiveIntegerField(default=1, verbose_name='구매 수량')),
                ('price_at_order', models.PositiveIntegerField(default=0, help_text='주문 시점의 상품 가격 (가격 변동 대비)', verbose_name='주문 시점 가격')),
                ('order_status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('PREPARING', '배송 준비 중'), ('SHIPPING', '배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '주문 취소'), ('REFUNDED', '환불 완료')], default='PENDING', max_length=20, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='주문')),
                ('product_item', models.ForeignKey(db_column='product_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='analyses.selectedproduct', verbose_name='상품 아이템')),
            ],
            options={
                'verbose_name': '주문 항목',
                'verbose_name_plural': '주문 항목 목록',
                'db_table': 'order_item',
            },
        ),
    ]
