# Generated by Django 4.2.11 on 2026-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('PREPARING', '배송 준비 중'), ('SHIPPING', '배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '주문 취소'), ('REFUNDED', '환불 완료')], default='PENDING', max_length=20, verbose_name='주문 상태'),
        ),
    ]
