# Generated by Django 4.2.11 on 2026-01-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        # 1. 필드 이름 변경 (product_item -> selected_product)
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_item',
            new_name='selected_product',
        ),
        # 2. DB 컬럼 이름 변경 (product_item_id -> selected_product_id)
        migrations.RunSQL(
            sql='ALTER TABLE order_item RENAME COLUMN product_item_id TO selected_product_id;',
            reverse_sql='ALTER TABLE order_item RENAME COLUMN selected_product_id TO product_item_id;',
        ),
    ]
