# Generated by Django 4.2.11 on 2026-01-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='브랜드명')),
                ('product_name', models.CharField(max_length=500, verbose_name='상품명')),
                ('product_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='상품 URL')),
                ('selling_price', models.PositiveIntegerField(default=0, verbose_name='판매가')),
                ('product_image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='상품 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 목록',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SizeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=50, verbose_name='사이즈 값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='size_codes', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '사이즈 코드',
                'verbose_name_plural': '사이즈 코드 목록',
                'db_table': 'size_code',
            },
        ),
    ]
