# Generated by Django 4.2.11 on 2026-01-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizecode',
            name='size_group',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='free', max_length=100, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='sizecode',
            name='product',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_codes', to='products.product', verbose_name='상품'),
        ),
        migrations.DeleteModel(
            name='SizeGroup',
        ),
    ]
