# Generated by Django 4.2.11 on 2026-01-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # MySQL prefix index: product_url의 첫 255자만 인덱싱 (255 * 4 = 1020 bytes < 3072)
        migrations.RunSQL(
            sql="CREATE INDEX idx_product_url ON product (product_url(255));",
            reverse_sql="DROP INDEX idx_product_url ON product;",
        ),
    ]
